# Generated by Django 5.2.15 on 2026-06-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_branch_created_at_branch_is_active_course_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
