# Generated by Django 5.2.15 on 2026-06-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_user_email_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('finished', 'Finished')], default='enrolled', max_length=20),
        ),
    ]
