# Generated by Django 5.2.15 on 2026-06-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_student_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
