# Generated by Django 4.2.30 on 2026-06-20 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_group_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('debt', 'Debt')], default='debt', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
