# Generated by Django 5.2.15 on 2026-06-20 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_enrollment_payment_status_alter_enrollment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
