# Generated by Django 5.2.15 on 2026-06-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
