# Generated by Django 5.2.15 on 2026-06-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_enrollment_debt_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_days_at',
            field=models.CharField(choices=[('Mon-Wed-Fri', 'Mon-Wed-Fri'), ('Tue-Thur-Sat', 'Tue-Thur-Sat'), ('Everyday', 'Everyday')], default='Mon-Wed-Fri', max_length=20),
        ),
    ]
