# Generated by Django 5.2.15 on 2026-06-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_group_group_days_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('canceled', 'Canceled')], default='accepted', max_length=20),
        ),
    ]
