# Generated by Django 5.2.15 on 2026-07-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrolled_free',
            field=models.BooleanField(default=False),
        ),
    ]
