# Generated by Django 5.2.15 on 2026-07-04 12:17

import django.db.models.deletion
import management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_enrollment_enrolled_free'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', management.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='teacher_share',
            field=models.IntegerField(default=50, help_text="Teacher's revenue share percentage"),
        ),
        migrations.AddField(
            model_name='payment',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.student'),
        ),
    ]
