# Generated by Django 5.2.15 on 2026-07-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_alter_payment_status_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='pdf_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
