# Generated by Django 4.2.30 on 2026-07-10 03:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_enrollment_pdf_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('absence', 'Absence Alert'), ('payment_pending', 'Payment Pending Confirmation'), ('payment_accepted', 'Payment Accepted'), ('lead_alert', 'Lead Alert')], default='absence', max_length=50),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('coming', 'Coming'), ('not_coming', 'Not Coming'), ('converted', 'Converted')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='management.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='management.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
