# Generated by Django 5.2.15 on 2026-07-10 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_alter_notification_notification_type_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='management.branch'),
        ),
    ]
